#!/bin/sh
#
#newpref sets directory name with date, more
#like normal linux packages.
if [ $# != 1 ]
then
	echo  Usage: BLDLIBDWARFTAR yyyymmdd
	echo  Example: BLDLIBDWARFTAR 20040108
	exit 1
fi
echo "This does not do UPDATEDWARFDUMPVERSION.sh"
dat=$1

tmpf=dwarf
tmpdir=/var/tmp
sh CPTOPUBLIC  $tmpdir/$tmpf
newpref=dwarf-${dat}
newf=libdwarf-${dat}.tar
echo src is $tmpdir/$tmpf tmp is $newpref target is $newf
#sh UPDATEDWARFDUMPVERSION.sh
echo ============  $newpref  $newf ==========

echo First create $tmpdir/$newpref with the latest source.
cd $tmpdir
if [ ! -d $tmpf ]
then
	echo No $tmpdir/dwarf present!  Do nothing.
	exit 0
fi
rm -rf $newpref

cp -r $tmpf $newpref
# Alter date below before using.e
rm -f ${newf} ${newf}.gz
tar cf /var/tmp/$newf $newpref
gzip ${newf}
hm=/home/davea/sgiweb3/pagedata
cp  ${newf}.gz $hm
ls -l $tmpdir/${newf}.gz
ls -l $hm/${newf}.gz
exit 0
