#!/bin/sh
#
bldone () {
  t=$1 
  cd $t
  #rm $t
  touch *.c *.cc *.h
  ./configure
  if [ $? != 0 ]
  then
	echo build failed
	exit
  fi
  make
  if [ $? != 0 ]
  then
	  echo build failed
	  exit
  fi
  cd ..
}

bldone libdwarf 
bldone dwarfdump
bldone dwarfdump2




