#!/bin/sh
if [ $# -eq 1 ]
then
  t=$1
else
  t=/var/tmp/dwarf
fi

echo target is $t
sh UPDATEDWARFDUMPVERSION.sh
rm -rf $t
mkdir $t
mkdir $t/dwarfdump 
mkdir $t/dwarfdump2
mkdir $t/libdwarf
mkdir $t/dwarfgen
mkdir $t/dwarfexample
mkdir $t/libdwarf/cmplrs
cp BLDLIBDWARF $t
for i in dwarfexample/NEWS \
dwarfexample/ChangeLog2010 \
dwarfexample/ChangeLog2009 \
dwarfexample/ChangeLog \
dwarfexample/simplereader.c \
dwarfexample/frame1.c \
dwarfexample/Makefile 
do
   cp -p $i $t/$i
done
for i in dwarfdump2/DWARFDUMPCOPYRIGHT \
dwarfdump2/tag_tree.list \
dwarfdump2/tag_tree_ext.list \
dwarfdump2/dwarfdump.1 \
dwarfdump2/dwarfdump.cc \
dwarfdump2/fderegs.h \
dwarfdump2/globals.h \
dwarfdump2/naming.cc \
dwarfdump2/naming.h \
dwarfdump2/tag_attr.list  \
dwarfdump2/tag_attr_ext.list  \
dwarfdump2/tag_common.h  \
dwarfdump2/tag_common.cc  \
dwarfdump2/tag_attr.list  \
dwarfdump2/Makefile.in  \
dwarfdump2/tag_tree.cc  \
dwarfdump2/configure  \
dwarfdump2/configure.in \
dwarfdump2/common.cc  \
dwarfdump2/common.h  \
dwarfdump2/dieholder.h \
dwarfdump2/dwconf.cc  \
dwarfdump2/dwconf.h  \
dwarfdump2/print_abbrevs.cc \
dwarfdump2/print_aranges.cc \
dwarfdump2/print_die.cc  \
dwarfdump2/print_frames.cc  \
dwarfdump2/print_lines.cc \
dwarfdump2/print_locs.cc \
dwarfdump2/print_macros.cc \
dwarfdump2/print_pubnames.cc \
dwarfdump2/print_ranges.cc \
dwarfdump2/print_static_funcs.cc \
dwarfdump2/print_static_vars.cc \
dwarfdump2/print_strings.cc \
dwarfdump2/print_types.cc \
dwarfdump2/print_weaknames.cc \
dwarfdump2/ChangeLog2010  \
dwarfdump2/ChangeLog2009  \
dwarfdump2/ChangeLog  \
dwarfdump2/srcfilesholder.h \
dwarfdump2/tag_attr.cc  \
dwarfdump2/dwarfdump.conf  \
dwarfdump2/NEWS  \
dwarfdump2/print_frames.h  \
dwarfdump2/COPYING  \
dwarfdump2/print_reloc.cc  \
dwarfdump2/print_sections.cc \
dwarfdump2/print_sections.h \
dwarfdump2/strstrnocase.cc \
dwarfdump2/config.h.in \
dwarfdump2/README \
dwarfdump2/GPL.txt \
dwarfdump2/install.sh \
dwarfdump2/uri.cc \
dwarfdump2/uri.h 
do
	cp -p $i $t/$i
done
for i in dwarfdump/addrmap.c \
dwarfdump/addrmap.h \
dwarfdump/makename.c \
dwarfdump/esb.h \
dwarfdump/DWARFDUMPCOPYRIGHT \
dwarfdump/tag_tree.list \
dwarfdump/tag_tree_ext.list \
dwarfdump/dwarfdump.1 \
dwarfdump/dwarfdump.c \
dwarfdump/globals.h \
dwarfdump/naming.c \
dwarfdump/naming.h \
dwarfdump/tag_attr.list  \
dwarfdump/tag_attr_ext.list  \
dwarfdump/tag_common.h  \
dwarfdump/tag_common.c  \
dwarfdump/tag_attr.list  \
dwarfdump/Makefile.in  \
dwarfdump/tag_tree.c  \
dwarfdump/checkutil.c  \
dwarfdump/checkutil.h  \
dwarfdump/configure  \
dwarfdump/configure.in \
dwarfdump/common.h  \
dwarfdump/common.c  \
dwarfdump/esb.c  \
dwarfdump/dwconf.c  \
dwarfdump/dwconf.h  \
dwarfdump/print_abbrevs.c \
dwarfdump/print_aranges.c \
dwarfdump/print_die.c  \
dwarfdump/print_frames.c  \
dwarfdump/print_lines.c \
dwarfdump/print_locs.c \
dwarfdump/print_macros.c \
dwarfdump/print_pubnames.c \
dwarfdump/print_ranges.c \
dwarfdump/print_reloc.h \
dwarfdump/print_static_funcs.c \
dwarfdump/print_static_vars.c \
dwarfdump/print_strings.c \
dwarfdump/print_types.c \
dwarfdump/print_weaknames.c \
dwarfdump/ChangeLog2010  \
dwarfdump/ChangeLog2009  \
dwarfdump/ChangeLog2008  \
dwarfdump/ChangeLog2007  \
dwarfdump/ChangeLog2006  \
dwarfdump/ChangeLog  \
dwarfdump/strstrnocase.c  \
dwarfdump/tag_attr.c  \
dwarfdump/dwarfdump.conf  \
dwarfdump/NEWS  \
dwarfdump/print_frames.h  \
dwarfdump/COPYING  \
dwarfdump/print_reloc.c  \
dwarfdump/print_sections.c \
dwarfdump/print_sections.h \
dwarfdump/config.h.in \
dwarfdump/testesb.c \
dwarfdump/README \
dwarfdump/GPL.txt \
dwarfdump/makename.h \
dwarfdump/install.sh  \
dwarfdump/uri.c \
dwarfdump/uritablebuild.c \
dwarfdump/uri.h 
do
	cp -p $i $t/$i
done
for i in libdwarf/pro_alloc.h \
libdwarf/pro_line.h \
libdwarf/pro_frame.c \
libdwarf/common.c \
libdwarf/common.h \
libdwarf/dwarf_addr_finder.c \
libdwarf/dwarf_loc.h \
libdwarf/dwarf_init_finish.c \
libdwarf/dwarf_elf_access.h \
libdwarf/dwarf_elf_access.c \
libdwarf/dwarf_original_elf_init.c \
libdwarf/dwarf_funcs.c \
libdwarf/dwarf_form.c \
libdwarf/gennames.c \
libdwarf/dwarf_harmless.c \
libdwarf/dwarf_harmless.h \
libdwarf/pro_util.h \
libdwarf/pro_opaque.h \
libdwarf/pro_reloc_stream.c \
libdwarf/LIBDWARFCOPYRIGHT \
libdwarf/index.v2.pdf \
libdwarf/dwarf_macro.h \
libdwarf/pro_alloc.c \
libdwarf/pro_die.c \
libdwarf/dwarf_global.h \
libdwarf/dwarf_base_types.h \
libdwarf/dwarf_sort_line.c \
libdwarf/pro_macinfo.c \
libdwarf/dwarf_print_lines.c \
libdwarf/pro_reloc.c \
libdwarf/pro_forms.c \
libdwarf/dwarf_arange.h \
libdwarf/pro_section.c \
libdwarf/dwarf_error.h \
libdwarf/pro_die.h \
libdwarf/dwarf_types.c \
libdwarf/dwarf_frame2.c \
libdwarf/dwarf_frame.h \
libdwarf/pro_arange.c \
libdwarf/dwarf_alloc.h \
libdwarf/dwarf_weaks.h \
libdwarf/dwarf_vars.h \
libdwarf/dwarf_macro.c \
libdwarf/dwarf_line2.c \
libdwarf/dwarf_funcs.h \
libdwarf/dwarf_ranges.c \
libdwarf/dwarf_stubs.c \
libdwarf/dwarf_incl.h \
libdwarf/dwarf_opaque.h \
libdwarf/dwarf_global.c \
libdwarf/libdwarf2p.1.pdf \
libdwarf/dwarf_query.c \
libdwarf/bldDWindex.sh \
libdwarf/dwarf_frame3.c \
libdwarf/libdwarfdefs.h \
libdwarf/dwarf_string.c \
libdwarf/pro_encode_nm.c \
libdwarf/pro_weaks.c \
libdwarf/Makefile.in \
libdwarf/LGPL.txt \
libdwarf/libdwarf.h \
libdwarf/libdwarf2.1.mm \
libdwarf/pro_reloc_symbolic.h \
libdwarf/configure \
libdwarf/configure.in  \
libdwarf/pro_funcs.c \
libdwarf/pro_arange.h \
libdwarf/pro_reloc_stream.h \
libdwarf/pro_finish.c \
libdwarf/malloc_check.c \
libdwarf/pro_types.c \
libdwarf/dwarf.h \
libdwarf/pro_init.c \
libdwarf/ChangeLog2010 \
libdwarf/ChangeLog2009 \
libdwarf/ChangeLog2008 \
libdwarf/ChangeLog2007 \
libdwarf/ChangeLog2006 \
libdwarf/ChangeLog \
libdwarf/pro_macinfo.h \
libdwarf/libdwarf2p.1.mm \
libdwarf/dwarf_line.h \
libdwarf/dwarf_error.c \
libdwarf/dwarf_arange.c \
libdwarf/dwarf_frame.c \
libdwarf/NEWS \
libdwarf/dwarf_types.h \
libdwarf/pro_line.c \
libdwarf/dwarf_line.c \
libdwarf/CHANGES \
libdwarf/dwarf_abbrev.c \
libdwarf/malloc_check.h \
libdwarf/pro_pubnames.c \
libdwarf/dwarf_pubtypes.c \
libdwarf/dwarf_util.h  \
libdwarf/pro_reloc.h  \
libdwarf/dwarf_weaks.c  \
libdwarf/pro_incl.h  \
libdwarf/cmplrs/dwarf_addr_finder.h \
libdwarf/mips_extensions.pdf \
libdwarf/libdwarf2.1.pdf \
libdwarf/pro_encode_nm.h \
libdwarf/pro_error.h \
libdwarf/dwarf.v2.pdf \
libdwarf/pro_reloc_symbolic.c \
libdwarf/pro_expr.c \
libdwarf/dwarf_loc.c \
libdwarf/pro_types.h \
libdwarf/dwarf_die_deliv.h \
libdwarf/dwarf_die_deliv.c \
libdwarf/pro_error.c \
libdwarf/COPYING \
libdwarf/dwarf_alloc.c  \
libdwarf/config.h.in  \
libdwarf/README  \
libdwarf/pro_vars.c  \
libdwarf/index.v2.mm  \
libdwarf/dwarf_vars.c  \
libdwarf/mips_extensions.mm  \
libdwarf/pro_frame.h  \
libdwarf/pro_expr.h  \
libdwarf/dwarf_abbrev.h  \
libdwarf/dwarf_util.c  \
libdwarf/pro_section.h  \
libdwarf/install.sh  \
libdwarf/dwarf.v2.mm  \
libdwarf/dwarf_leb.c  
do
	cp -p $i $t/$i
done
for i in dwarfgen/config.h.in \
dwarfgen/createirepformfrombinary.cc \
dwarfgen/createirepfrombinary.cc  \
dwarfgen/dwarfgen.cc \
dwarfgen/irepattrtodbg.cc \
dwarfgen/ireptodbg.cc \
dwarfgen/configure.in \
dwarfgen/createirepfrombinary.h	\
dwarfgen/general.h \
dwarfgen/irepattrtodbg.h \
dwarfgen/irepdie.h \
dwarfgen/irepform.h \
dwarfgen/irepframe.h \
dwarfgen/irepmacro.h \
dwarfgen/irepresentation.h \
dwarfgen/ireptodbg.h \
dwarfgen/strtabdata.h  \
dwarfgen/COPYING \
dwarfgen/configure \
dwarfgen/dwarfgen.1 \
dwarfgen/GPL.txt \
dwarfgen/install.sh  \
dwarfgen/Makefile.in \
dwarfgen/ChangeLog \
dwarfgen/README 
do
	cp -p $i $t/$i
done
