#!/bin/bash
# CLEANUP
l=`pwd`
echo $l
lb=`basename $l`
ld=`dirname $l`
#echo " lb: $lb"
#echo " ld: $ld"
cdtarg=.
sloc=$l/scripts
if [ x$lb = "xscripts" ]
then
  #echo "ld: $ld"
  ldb=`basename $ld`
  #echo "ldb: $ldb"
  if [ x$ldb = "xcode" ]
  then
     cdtarg=..
     sloc=$l
  else
     echo "Run from */code, not $l , giving up."
     exit 1
  fi
  cd $cdtarg
  if [ $? -ne 0 ]
  then
     echo "cd $cdtarg failed, giving up."
     exit 1
  fi
else
  if [ x$lb = "xcode" ]
  then
    cdtarg="."
  else
    echo "Run from */code, not $l , giving up."
    exit 1
  fi
  # No need to cd.
fi
l=`pwd`
#echo "Now at $l"
#echo "sloc $sloc"


( cd dwarfexample ; make clean ;  make distclean )
( cd dwarfgen ; make clean ;  make distclean )
( cd libdwarf ; make clean ;  make distclean )
( cd dwarfdump ; make clean ;  make distclean )
( cd bugxml ; rm -f bugrecord.pyc )
( cd bugxml ; rm -f dwarfbug.xml )
( cd bugxml ; rm -f dwarfbugtail )
( cd bugxml ; rm -f junk* )
( cd bugxml ; rm -rf __pycache__ )

rm -f libdwarf/BLD
rm -f dwarfdump/BLD

rm -f dwarfgen/configure.lineno
rm -f ALLd*
rm -f junk* */junk*
