name: ci_mac_cmake

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos_cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name:  cmake
      run:  |
        mkdir builddir && cd builddir
        cmake -G Ninja -DDO_TESTING=YES -DINSTALL_STATIC_LIBRARIES=YES -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
        ninja
        ninja test

