name: macautotool

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
 macos_autotools:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: tools
      run: | 
        export HOMEBREW_REQUIRE_TAP_TRUST=1
        brew install automake libtool
    - name: aclocal
      run: aclocal
    - name: autoreconf
      run: autoreconf --warnings=all  -vif
    - name: config
      run: ./configure --enable-dwarfexample --enable-wall
    - name: make
      run:  |
        make
        make check

