name: macos_autotools CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

# command line tools and autotools needed. How?
    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: /usr/local/bin/autoreconf -vif
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
